### ISSUE TITLE
Using tail to watch "current"

### ISSUE THREAD

**Issue by opeeba** [cdown/checkupdates-cron#1]
Consider changing line 27 to:

> cp "$dir/current" "$dir/last"

Using mv results in the following error:

> tail: ‘/var/tmp/checkupdates-cron.opeeba/current’ has become inaccessible: No such file or directory
> tail: ‘/var/tmp/checkupdates-cron.opeeba/current’ has appeared;  following end of new file

I can use 2>/dev/null to eliminate the output if there is any reason to prefer mv.

**Comment by cdown** [comment]
I'm not convinced `tail` is the right tool for this job (unless you have a specific reason). This shouldn't happen with `watch cat /var/tmp/checkupdates-cron.opeeba/current`.

**Comment by cdown** [comment]
Note, you can also use `tail -F`.
