### ISSUE TITLE
merge upstream or create package

### ISSUE THREAD

**Issue by ilf** [cdown/checkupdates-cron#2]
Thanks for this, I've been using it for years.

It would be great to have this included upstream. Did you ever ask upstream to include it in pacman-contrib? That would be really cool.

Alternatively, would you like to package this as Arch package?

Thanks, and keep up the good work!

**Comment by cdown** [comment]
Hi there! I've not used this for several years, and instead just precache: https://github.com/cdown/ansible-server/blob/master/files/bin/cache-updates

Feel free to solicit upstream opinions though.

**Comment by ilf** [comment]
This feature is now merged natively in checkupdates: https://gitlab.archlinux.org/pacman/pacman-contrib/-/issues/29

Thanks for your inspiration!
